### ISSUE TITLE
Some People get errors when client connects to there localhost, as if its IPv6 address. And some other issues

### ISSUE THREAD

**Issue by LiamKarlMitchell** [LiamKarlMitchell/InfiniteSky#107]
http://stackoverflow.com/questions/24896386/request-connection-remoteaddress-now-prefixed-in-ffff-in-node-js
````
Error: Invalid byte: ::ffff:127
Tue Feb 24 2015 09:15:41 GMT+0200 (GTB Standard Time)
Stacktrace:
     at ip2long (C:\Users\Anostali\Documents\InfiniteSky\node_modules\netmask\li
b\netmask.js:19:44)
    at Netmask.contains (C:\Users\Anostali\Documents\InfiniteSky\node_modules\ne
tmask\lib\netmask.js:88:17)
    at Object.GameStart [as function] (C:\Users\Anostali\Documents\InfiniteSky\p
ackets\login\handleGameStart.js:38:27)
    at Socket.onData (C:\Users\Anostali\Documents\InfiniteSky\CachedBuffer.js:11
7:41)
    at Socket.<anonymous> (C:\Users\Anostali\Documents\InfiniteSky\CachedBuffer.
js:170:18)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)
````

Temp solution disable IPv6 from network settings.

**Comment by LiamKarlMitchell** [comment]
Add to util.js

````
// If for some reason an IPv6 address is given we want to strip off the
  // junk and just get our IPv4 address
  cleanIP: function(ip) {
    return ip.substr(ip.lastIndexOf(':')+1);
  },

````

And patch world and login etc to use it.

**Comment by LiamKarlMitchell** [comment]
Fix error in CVec3 missing ,
Fix error in world.js addSocketToTransferQueue the setTimeout should just be setTimeout not socket.setTimeout.

**Comment by LiamKarlMitchell** [comment]
Resolved
