### ISSUE TITLE
Fix failed to load bson on start up.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [LiamKarlMitchell/InfiniteSky#208]
Error: The specified procedure could not be found.
\\?\InfiniteSky\FruitSalad\node_modules\bson\build\Release\bson.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (InfiniteSky\FruitSalad\node_modules\bson\ext\index.js:15:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by seid96** [comment]
how to fix ?
